# Generated by Django 5.2.3 on 2025-08-27 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiabetesHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.FloatField()),
                ("gender", models.CharField(max_length=10)),
                ("hypertension", models.BooleanField()),
                ("heart_disease", models.BooleanField()),
                ("smoking_history", models.CharField(max_length=20)),
                ("bmi", models.FloatField()),
                ("hba1c_level", models.FloatField()),
                ("blood_glucose_level", models.FloatField()),
                ("result", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
