# Generated by Django 5.2.3 on 2025-11-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes_predictor', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabeteshistory',
            name='medicine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
