# Generated by Django 5.2.3 on 2025-11-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes_predictor', '0003_diabeteshistory_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabeteshistory',
            name='medicine',
            field=models.TextField(default=''),
        ),
    ]
